mit_directory:
    resource: "@MITDirectoryBundle/Resources/config/routing.yml"
    prefix:   /

mit_finance:
    resource: "@MITFinanceBundle/Resources/config/routing.yml"
    prefix:   /finance
app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

