<?php

namespace MIT\FinanceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteRepository extends EntityRepository
{
}
